### PR TITLE
add: signup,signin,forgot-pass

### PR DESCRIPTION
**Pull request by thegeorgenikhil**
added 
- Signup [Link](https://deploy-preview-2--quizz-up.netlify.app/pages/signup.html)
- Signin [Link](https://deploy-preview-2--quizz-up.netlify.app/pages/signin.html)
- Forgot Password Page [Link](https://deploy-preview-2--quizz-up.netlify.app/pages/forgot.html)

### CODE REVIEW

**Comment by anandsr21harshit** [comment]
-All looks good
-Checked deployed link and it is responsive as well
- Good css practice used

One slight distortion I found here:
image

Check box and text are not aligned properly.
You can correct it.

Approving as everything looks fine

**Review by anandsr21harshit — APPROVED** [review]
Can be merged to dev

**Review by romabulani — APPROVED** [review]
Good to merge

**Comment by thegeorgenikhil** [comment]
@anandsr21harshit thank you for pointing that, Fixed it now!

**Pull request merged**
